name: asro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  animate_do: ^3.3.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

  flutter_lints: ^3.0.0

flutter:

 # dart run build_runner build --delete-conflicting-outputs

  uses-material-design: true

  assets:
    - .env.dev
    - .env.production
    - assets/images/core/empty_screen.png
    - assets/images/core/no_network.jpg
    - assets/images/core/splash.jpg
    - assets/images/core/page_under_build.jpg
    - assets/icons/play_store_512.png
    - assets/images/core/splash_ios_android_11.png
    - assets/images/core/splash_android_12.png
    - lang/ar.json
    - lang/en.json
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
